### ISSUE TITLE
Implement all researched packets

### ISSUE THREAD

**Issue by hertzg** [hertzg/metekcity#4]
So far the `notes.txt` contains samples saved during research, this issue tries to collect the status of implementation of each packet type. Some of them might need their own issue but here they are represented all togeather.

# Packet Types:

- [x] `SET_UNIT` (`0xc0`) - c5736b4, - #2
- [x] `SET_TARE` (`0xc1`) - #2
- [x] `SET_AUTO_OFF` (`0xc4`) - 805a076, #2
- [x] `MEASUREMENT` (`0xd0`) - bfcf5df
- [x] `UNIT_STATE` (`0xd1`) - #5 
- [x] `TARE_STATE` (`0xd3`) - bfcf5df, #3
- [x] `AUTO_OFF_STATE` (`0xd5`) - #2
- [x] `ERROR_STATE` (`0xe0`) - bfcf5df, #3
- [x] `ITEM_STATE` (`0xe4`) - bfcf5df, #3

# Unresearched packets

- `SET_NUTRITION` (`0xc2`)
-  `?PING` (`0xc3`)
-  `???` (`0xd2`)
-  `?PONG` (`0xd4`)
-  `???` (`0xe1`)
-  `???` (`0xe2`)
-  `???` (`0xe3`)

# Packet Details

| Status | Type             | Source(s) | Payload                 | Generic?                       | Notes                                                                   |
| ------ | ---------------- | --------- | ----------------------- | ------------------------------ | ----------------------------------------------------------------------- |
| ✅     | `SET_UNIT`       | `COMMAND` | `unit`                  | `uint8Parselizer`              |                                                                         |
| ✅     | `SET_TARE`       | `COMMAND` | `shouldReset`           | `booleanParselizer`            |                                                                         |
| ✅     | `SET_AUTO_OFF`   | `COMMAND` | `timeout`               | `uint8Parselizer`              |                                                                         |
| ✅     | `MEASUREMENT`    | `NOTIFY`  | `sign`, `value`, `unit` | `uint8Parselizer`              |                                                                         |
| ✅     | `TARE_STATE`     | `NOTIFY`  | `isOn`                  | `booleanParselizer` (inverted) |                                                                         |
| ✅     | `AUTO_OFF_STATE` | `NOTIFY`  | `timeout`               | `uint16Parselizer`             | the value is the same as for command with the exception of extra 0 byte |
| ✅     | `ERROR_STATE`    | `NOTIFY`  | `isOn`                  | `booleanParselizer` (inverted) |                                                                         |
| ✅     | `ITEM_STATE`     | `NOTIFY`  | `isOn`                  | `booleanParselizer` (inverted) |                                                                         |
| ✅     | `UNIT_STATE`     | `NOTIFY`  | `unit`                  | `uint8Parselizer`              |                                                                         |
| 🛑      | `SET_NUTRITION`  | `COMMAND` | (complex object)        |                                |                                                                         need more samples to understad how data is encoded |

## Legend

| Marker    | Category  | Description                           |
| --------- | --------- | ------------------------------------- |
| ⌛        | Status    | Waiting (todo)                        |
| 🛑         | Status    | Blocked                        |
| ✅        | Status    | Done                                  |
| `COMMAND` | Source(s) | Command send to the Device            |
| `NOTIFY`  | Source(s) | Notification received from the Device |

**Comment by hertzg** [comment]
Closing this for now as all the researched packets have been implemented.
